version: '3'
services:
    rhasspy:
        image: "rhasspy/rhasspy:latest"
        container_name: rhasspy-sat
        restart: unless-stopped
        volumes:
            - "/home/pi/HomeAutomation/rhasspy-sat/profiles:/profiles"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "12101:12101"
            - "12333:12333"
            - "12183:12183"
        devices:
            - "/dev/snd:/dev/snd"
        command: --user-profiles /profiles --profile en
        network_mode: host
